; PlatformIO Project Configuration File

[platformio]
; Build both if you click Build, or choose one environment explicitly.
default_envs = nodemcu_env, supermini_env

; =========================================================
; ESP32 NodeMCU project
; =========================================================
[env:nodemcu_env]
platform = espressif32
board = esp32dev
framework = arduino

src_dir = ESP32_NodeMCU
monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    crankyoldgit/IRremoteESP8266
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP


; =========================================================
; ESP32-C3 Super Mini project
; =========================================================
[env:supermini_env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

src_dir = ESP32_C3_Supermini
monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
    crankyoldgit/IRremoteESP8266
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP