[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
  bblanchon/ArduinoJson
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor
  crankyoldgit/IRremoteESP8266
  ESP32Async/ESPAsyncWebServer
  ESP32Async/AsyncTCP